export enum RolesEnum {
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    ADMIN_COMPANY = 'ADMIN_COMPANY',
    COMITEE_MEMBER = 'COMITEE_MEMBER',
    RESIDENT = 'RESIDENT',
    TENANT = 'RENTER',
    VIGILANCE = 'VIGILANCE'
}
